name: graphx
description: Render API on top of CustomPainter to power-up your Flutter apps to the next level.
version: 1.0.12
homepage: https://github.com/roipeker/graphx

environment:
  sdk: ">=2.19.0 <4.0.0"
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  xml: ^6.5.0
  http: ^1.1.2
  flutter_svg: ^1.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1